title: Shahab Sotudian
description: ML Engineer
site_title: '@ss - Shahab Sotudian'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Sotudian
blog_url: https://www.Sotudian.com
email: Sotudian@bu.edu
keybase_username: Sotudian
twitter_username: Sotudian
reddit_username: Sotudian

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
