title: Shahab Sotudian
description: Machine Learning Researcher
site_title: 'Shahab Sotudian'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Sotudian
blog_url: https://connects.catalyst.harvard.edu/Profiles/display/Person/212376/Network/SimilarTo
email: Sotudian@bu.edu
keybase_username: Sotudian
twitter_username: s_sotudian
reddit_username: Sotudian

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
